title: CAPSLOCK
email: yechielsul@gmail.com
description: CAPSLOCK is a movement to help improve the coding level of students of BMDC
baseurl: "/capslock-website"
url: "https://capslock-bmdc.github.io/""
twitter_username: donthave_1
github_username:  sulzy3

# Build settings
environment: production
theme: minima
plugins:
  - jekyll-feed
