title: CAPSLOCK
email: yechielsul@gmail.com
description: CAPSLOCK is a movement to help improve the coding level of students of BMDC
baseurl: ""
url: ""
twitter_username: donthave_1
github_username:  sulzy3

# Build settings
theme: minima
plugins:
  - jekyll-feed